# Site settings
email: okay@samesies.io
baseurl: ""
google_analytics: 

name: Thomas Vaeth
title: Samesies
description: >
  Samesies is a web development agency started by Thomas Vaeth and based in Seattle, WA. We create minimal themes for Ghost, Jekyll, and WordPress. ğŸ‘¨â€ğŸ’»ğŸ‘©â€ğŸ’»
url: "http://samesies.io"
twitter_username: thomasvaeth
default_img: http://samesies.io/assets/images/seo.jpg

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  - octopress-autoprefixer
sass:
  style: compressed
exclude:
  - node_modules
  - .DS_Store
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json

# Collections
collections:
  themes:
    output: true
    permalink: "/themes/:path"
  documentation:
    output: true
    permalink: "/documentation/:path"
